### ISSUE TITLE
Modification de la page de suggestions

### ISSUE THREAD

**Issue by Skiso** [Feeew/Pronostiques#1]
Bonjour ,

j'aimerai te proposer une modification dans ta page suggestions, en effet, j'ai créé une autre page qui traite l'importance de la demande. Et j'ai scindé la page actuelle en 3 tableaux différents : un tableau avec les suggestions faites, un autre avec les suggestions à faire, un autre avec les suggestions en attente.

Pour ce faire, j'ai du modifier la base de données et ajouter un champ dans la table suggestions, il s'agit d'un champ tinyInt qui possede 3 valeurs possible (1 : suggestion faites, 2 : suggestion à faire, 3 : suggestion en attente, et 4 suggestions poubelle).

Donnes moi des news,

Julien

**Comment by Feeew** [comment]
Super idée, merci pour la proposition et pour la réalisation, j'ai récupéré ton commit et ça marche parfaitement. ;-)
